import Head from "next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import css from '../styles/Home.module.css'
import Services from "../components/Services";
import client from "../lib/client";
import Menu from "../components/Menu";

export default function Home({pizza}) {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
          <Services/>
          <Menu pizzas={pizza}/>
        </main>
      </div>

    </Layout>

  );
}

// getServersideProps : this return json which used by pages. all this handled automatically by next.js (no need to write back end)
export const getServerSideProps = async () => { 

const pizza = await client.fetch(`*[_type == "pizza"]`);
  return{
    props:{
      pizza
    }
  };

}